### ISSUE TITLE
Controller Methods don't work

### ISSUE THREAD

**Issue by Sineos** [hobbyquaker/node-red-contrib-zigbee#65]
The controller methods do not work in v0.15. Example flow:

`
[{"id":"29703ee8.f95f9a","type":"zigbee-controller","z":"4efcfe78.a4103","shepherd":"af99cec.42625b","name":"controller","x":500,"y":740,"wires":[["d4ecc388.82299"]]},{"id":"d4ecc388.82299","type":"debug","z":"4efcfe78.a4103","name":"","active":false,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":710,"y":740,"wires":[]},{"id":"a835f900.ac54b","type":"inject","z":"4efcfe78.a4103","name":"","topic":"getNetworkParameters","payload":"true","payloadType":"bool","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":220,"y":740,"wires":[["29703ee8.f95f9a"]]},{"id":"af99cec.42625b","type":"zigbee-shepherd","z":"","name":"zigbee herdsman","path":"/dev/ttyACM0","baudRate":"115200","rtscts":true,"channelList":[25],"led":"disabled"}]
`

Most of the methods yield no result. Exceptions:

permitJoin: Works
enableLED / disableLED: `TypeError: this.herdsman.enableLED is not a function`
reset: didn't try - was too afraid ;-)

**Comment by Sineos** [comment]
For whatever reason the functions "healed" themselves with the switch to Z-Stack 3.
